version: '3'
services:
  websocket:
    env_file:
      - dev.env
    container_name: websocket_container
    build: .
    ports:
      - '9000:9000'      
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: bridge